class EditPlayerMatches < ActiveRecord::Migration[5.2]
  def change
     remove_column :player_matches, :ban_1, :string
     remove_column :player_matches, :ban_10, :string
     remove_column :player_matches, :ban_10_id, :integer
     remove_column :player_matches, :ban_1_id, :integer
     remove_column :player_matches, :ban_2, :string
     remove_column :player_matches, :ban_2_id, :integer
     remove_column :player_matches, :ban_3, :string
     remove_column :player_matches, :ban_3_id, :integer
     remove_column :player_matches, :ban_4, :string
     remove_column :player_matches, :ban_4_id, :integer
     remove_column :player_matches, :ban_5, :string
     remove_column :player_matches, :ban_5_id, :integer
     remove_column :player_matches, :ban_6, :string
     remove_column :player_matches, :ban_6_id, :integer
     remove_column :player_matches, :ban_7, :string
     remove_column :player_matches, :ban_7_id, :integer
     remove_column :player_matches, :ban_8, :string
     remove_column :player_matches, :ban_8_id, :integer
     remove_column :player_matches, :ban_9, :string
     remove_column :player_matches, :ban9_id, :integer
     remove_column :player_matches, :camps_cleared, :integer
     remove_column :player_matches, :conquest_losses, :integer
     remove_column :player_matches, :conquest_points, :integer
     remove_column :player_matches, :conquest_tier, :integer
     remove_column :player_matches, :conquest_wins, :integer
     remove_column :player_matches, :damage_bot, :integer
     remove_column :player_matches, :damage_done_in_hand, :integer
     remove_column :player_matches, :damage_done_magical, :integer
     remove_column :player_matches, :damage_done_physical, :integer
     remove_column :player_matches, :damage_taken_magical, :integer
     remove_column :player_matches, :damage_taken_physical, :integer
     remove_column :player_matches, :distance_traveled, :integer
     remove_column :player_matches, :duel_losses, :integer
     remove_column :player_matches, :duel_points, :integer
     remove_column :player_matches, :duel_tier, :integer
     remove_column :player_matches, :duel_wins, :integer
     remove_column :player_matches, :first_ban_side, :string
     remove_column :player_matches, :healing_bot, :integer
     remove_column :player_matches, :healing_player_self, :integer
     remove_column :player_matches, :item_id_1, :integer
     remove_column :player_matches, :item_id_2, :integer
     remove_column :player_matches, :item_id_3, :integer
     remove_column :player_matches, :item_id_4, :integer
     remove_column :player_matches, :item_id_5, :integer
     remove_column :player_matches, :item_id_6, :integer
     remove_column :player_matches, :item_active_1, :string
     remove_column :player_matches, :item_active_2, :string
     remove_column :player_matches, :item_active_3, :string
     remove_column :player_matches, :item_active_4, :string
     remove_column :player_matches, :item_purch_1, :string
     remove_column :player_matches, :item_purch_2, :string
     remove_column :player_matches, :item_purch_3, :string
     remove_column :player_matches, :item_purch_4, :string
     remove_column :player_matches, :item_purch_5, :string
     remove_column :player_matches, :item_purch_6, :string
     remove_column :player_matches, :joust_losses, :integer
     remove_column :player_matches, :joust_points, :integer
     remove_column :player_matches, :joust_tier, :integer
     remove_column :player_matches, :joust_wins, :integer
     remove_column :player_matches, :killing_spree, :integer
     remove_column :player_matches, :kills_bot, :integer
     remove_column :player_matches, :kills_double, :integer
     remove_column :player_matches, :kills_penta, :integer
     remove_column :player_matches, :kills_quadra, :integer
     remove_column :player_matches, :kills_siege_juggernaut, :integer
     remove_column :player_matches, :kills_single, :integer
     remove_column :player_matches, :kills_triple, :integer
     remove_column :player_matches, :kills_wild_juggernaut, :integer
     remove_column :player_matches, :map_game, :string
     remove_column :player_matches, :multi_kill_max, :integer
     remove_column :player_matches, :party_id, :integer
     remove_column :player_matches, :rank_stat_conquest, :integer
     remove_column :player_matches, :rank_stat_duel, :integer
     remove_column :player_matches, :rank_stat_joust, :integer
     remove_column :player_matches, :reference_name, :string
     remove_column :player_matches, :region, :string
     remove_column :player_matches, :skin, :string
     remove_column :player_matches, :skin_id, :integer
     remove_column :player_matches, :task_force, :integer
     remove_column :player_matches, :team_1_score, :integer
     remove_column :player_matches, :team_2_score, :integer
     remove_column :player_matches, :team_id, :integer
     remove_column :player_matches, :team_name, :string
     remove_column :player_matches, :winning_task_force, :integer
     remove_column :player_matches, :has_replay, :string
     remove_column :player_matches, :match_queue__id, :integer
     remove_column :player_matches, :name, :string
     remove_column :player_matches, :player_name, :string
     remove_column :player_matches, :active_id_1, :integer
     remove_column :player_matches, :active_id_2, :integer
     remove_column :player_matches, :active_id_3, :integer
     remove_column :player_matches, :active_id_4, :integer

     add_column :player_matches, :adj_gold_per_minute, :float
  end
end
